Add Comprehensive Rust 🦀
lborb/book pull request #59
Opened 2023-02-22 15:28 UTC by mgeisler

I would suggest adding the Comprehensive Rust 🦀 course to the list of introductory guides.

I put it after the "A Gentle Introduction To Rust" since it's similar in that it tries to cover all of the language (but it's much longer).

2023-02-22 16:07 UTC, glyn requested changes
Thanks for this - looks like a great resource (especially after confirming it has an OSS license). Shame about the cookies that Google want to foist on readers of the book, but that's not a show-stopper.

However, the lists of books are all in alphabetical order, so "A Gentle Introduction to Rust" just happens to be at the top of the unofficial/introductory list by virtue of this. Please could you move the new item down the list to preserve alphabetical order?

2023-02-25 16:08 UTC, mgeisler commented on src/unofficial.md
> +* [Comprehensive Rust 🦀](https://google.github.io/comprehensive-rust/) - a multi-day course developed by Google to teach Rust to Android engineers
```suggestion
```

2023-02-25 16:08 UTC, mgeisler commented on src/unofficial.md
>  * [`Dyner`](https://dyner.netlify.app/) - experimental trait (_dyn_) objects in Rust
```suggestion
* [Comprehensive Rust 🦀](https://google.github.io/comprehensive-rust/) - a multi-day course developed by Google to teach Rust to Android engineers
* [`Dyner`](https://dyner.netlify.app/) - experimental trait (_dyn_) objects in Rust
```

2023-02-25 16:19 UTC, mgeisler commented
> Shame about the cookies that Google want to foist on readers of the book, but that's not a show-stopper.

While researching how to publish the course to the world, I learned about the official [Google Analytics Opt-out Browser Add-on](https://tools.google.com/dlpage/gaoptout). You can of course trust this extension or not, all up to you :slightly_smiling_face:

> Please could you move the new item down the list to preserve alphabetical order?

Sure, it should be reordered now.

2023-02-25 16:36 UTC, glyn approved these changes
Thank you @mgeisler!

2023-02-25 16:37 UTC, merged

2023-02-25 17:25 UTC, mgeisler commented
Thanks!