Update official.md
lborb/book pull request #77
Opened 2024-01-19 12:58 UTC by Tbkhi

Changes the layout of the Working Groups section and add the Lang team homepage

2024-03-04 18:34 UTC, Tbkhi commented
Bumping that as "not spam".

2024-03-05 01:15 UTC, glyn requested changes
The convention, described in the README of this repo, is that each entry should start with a link containing the literal title of the book. So, for example, https://rust-lang.github.io/wg-async/ has title "wg-async" rather than this PR's "Async team working group", even though that is more explanatory. The description of the entry (after "-" is the place to clarify any confusing book titles).

2024-03-05 19:20 UTC, glyn commented on src/official.md
> +* [T-Lang](https://lang-team.rust-lang.org/design_notes.html) - information related to the work of the lang team
Let's use the proper title:
```suggestion
* [The Rust Language Design Team](https://lang-team.rust-lang.org/design_notes.html) - information related to the work of the lang team
```

2024-03-05 19:21 UTC, glyn commented on src/official.md
> +* [T-Types](https://rust-lang.github.io/types-team/) - traits implementation improvements
Let's use the proper title:
```suggestion
* [The Types Team](https://rust-lang.github.io/types-team/) - traits implementation improvements
```

2024-03-05 19:22 UTC, glyn commented on src/official.md
> +* [WG-Async](https://rust-lang.github.io/wg-async/) - foundations of async I/O
Let's use the same case as the title:
```suggestion
* [wg-async](https://rust-lang.github.io/wg-async/) - foundations of async I/O
```

2024-03-06 12:08 UTC, merged