Add contents rust offical
lborb/book pull request #84
Opened 2024-10-03 14:53 UTC by minatorak

bisect rustc project is new -> https://github.com/rust-lang/cargo-bisect-rustc/

2024-10-06 11:16 UTC, glyn requested changes
Thanks for this. Sorry for the slow response - I'm away from home at the moment.

Three simple bits of rework please.

2024-10-06 11:16 UTC, glyn commented on src/official.md
> +* [Const Generics Project Group](https://rust-lang.github.io/project-const-generics/index.html) - implements and designs the const_generics feature
Please could you move this to the top of that group so the book names are in alphabetical order?

2024-10-06 11:16 UTC, glyn commented on src/official.md
> +* [cargo bisect rustc](https://rust-lang.github.io/cargo-bisect-rustc/) - tool for automatically downloads rustc artifacts and tests until it finds the regression
Please could you move this so the book names in this group are in alphabetical order?

Also, please rename to `cargo-bisect-rust` to match the literal name of the book (compare `wg-async`).

2024-10-07 11:06 UTC, minatorak commented
thank for review

2024-10-07 15:53 UTC, glyn approved these changes
Looks good, thanks. Just tweaked the text a little.

2024-10-07 15:53 UTC, glyn commented on src/official.md
> +* [Const Generics Project Group](https://rust-lang.github.io/project-const-generics/index.html) - implements and designs the const_generics feature
```suggestion
* [Const Generics Project Group](https://rust-lang.github.io/project-const-generics/index.html) - design and implementation of the const generics feature
```

2024-10-07 15:53 UTC, glyn commented on src/official.md
> +* [cargo-bisect-rustc](https://rust-lang.github.io/cargo-bisect-rustc/) - tool for automatically downloads rustc artifacts and tests until it finds the regression
```suggestion
* [cargo-bisect-rustc](https://rust-lang.github.io/cargo-bisect-rustc/) - tool for automatically downloading and bisecting rustc artifacts and tests until it finds a given regression
```

2024-10-07 15:54 UTC, merged

2024-10-07 15:55 UTC, glyn commented
Thanks again @minatorak!