Add wasm-pack docs
lborb/book pull request #9
Opened 2021-01-23 04:57 UTC by neilweidinger

Thanks!

2021-01-23 10:42 UTC, glyn commented on src/unofficial.md
> +* [The `wasm-pack` Docs](https://rustwasm.github.io/docs/wasm-pack/)
As I mention in the README, my convention is to use the literal title of the book in question:
```suggestion
* [Hello wasm-pack!](https://rustwasm.github.io/docs/wasm-pack/)
```

2021-01-23 10:43 UTC, glyn requested changes
Thanks for this! Please could you change to use the literal title of the book for consistency with the other entries and as described in the README?

2021-01-25 06:13 UTC, neilweidinger commented
Fixed in the latest commit, cheers!

2021-01-25 09:48 UTC, glyn approved these changes
Looks good now, thanks.

2021-01-25 09:48 UTC, merged